# This workflow publishes package to pypi via poetry

name: Publish package

on:
  push:
    tags:
    - '*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.7, 3.8, 3.9]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2

      - name: Set poetry env
        run: |
          pip install --upgrade pip
          pip install taskipy cython toml
          poetry install
        shell: bash

      - name: Create tarball
        if: matrix.python-version == 3.7
        run: |
          poetry run build -f sdist
        shell: bash

      - name: Create wheel
        run: |
          poetry run build -f wheel
        shell: bash

      - name: Upload artifacts
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: dist/


  publish:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2

      - name: Clear dist folder
        run: |
          rm -rf dist/

      - name: Download
        uses: actions/download-artifact@v2
        with:
          name: artifacts
          path: dist/

      - name: Publish to PyPI
        if: success()
        run: |
          poetry publish -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }}
        shell: bash
